# Generated by Django 3.2.7 on 2021-09-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_apply_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply_job',
            name='website',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
